// Generated by gener8 - Do not edit by hand!


import {
Modifier,
DownloadResult
} from "../gener8-runtime/gener8-runtime";


/** Fleet Monitoring API
*/
// Source: cs-fleetmonitoring-api.gener8.yaml:45
export interface FleetMonitoringApi {

	/** Create a new vehicle
	*/
	createVehicle(command: CreateVehicleCommand): Promise<CreateVehicleResult>

	/** Modify a vehicle
	*/
	modifyVehicle(command: ModifyVehicleCommand): Promise<ModifyVehicleResult>

	/** Delete a vehicle
	*/
	deleteVehicle(command: DeleteVehicleCommand): Promise<DeleteVehicleResult>

	/** Create a new fleet
	*/
	createFleet(command: CreateFleetCommand): Promise<CreateFleetResult>

	/** Modify a fleet
	*/
	modifyFleet(command: ModifyFleetCommand): Promise<ModifyFleetResult>

	/** Delete a fleet
	*/
	deleteFleet(command: DeleteFleetCommand): Promise<DeleteFleetResult>

	/** Add a vehicle to a fleet
	*/
	addVehicleToFleet(command: AddVehicleToFleetCommand): Promise<AddVehicleToFleetResult>

	/** Remove a vehicle from a fleet
	*/
	removeVehicleFromFleet(command: RemoveVehicleFromFleetCommand): Promise<RemoveVehicleFromFleetResult>

	/** List fleets.
	*/
	getFleets(query: GetFleetsQuery): Promise<GetFleetsQueryResult>

	/** Get all the client vehicles
	*/
	getVehicles(query: GetVehiclesQuery): Promise<GetVehiclesQueryResult>

	/** Get the vehicles
	*/
	getFleetVehicles(query: GetFleetVehiclesQuery): Promise<GetFleetVehiclesQueryResult>

	/** Get the vehicle positions
	*/
	getVehiclePositions(query: GetVehiclePositionsQuery): Promise<GetVehiclePositionsQueryResult>

	/** Get all the client KPIs
	*/
	getKpis(query: GetKpisQuery): Promise<GetKpisQueryResult>
}
/** User Settings API
*/
// Source: cs-settings-api.gener8.yaml:5
export interface UserSettingsApi {

	/** Delete settings
	*/
	deleteUserSettings(command: DeleteUserSettingsCommand): Promise<DeleteUserSettingsResult>

	/** Save User settings
	*/
	saveUserSettings(command: SaveUserSettingsCommand): Promise<SaveUserSettingsResult>

	/** Retrieve a setting
	*/
	getUserSetting(query: GetUserSettingQuery): Promise<GetUserSettingQueryResult>

	/** Retrieve multiple settings
	*/
	getUserSettings(query: GetUserSettingsQuery): Promise<GetUserSettingsQueryResult>
}
/** Notifications API
*/
// Source: cs-notifications-api.gener8.yaml:6
export interface NotificationsApi {

	/** Delete notifications
	*/
	markNotifications(command: MarkNotificationsCommand): Promise<MarkNotificationsResult>

	/** Retrieves current notifications
	*/
	getCurrentNotifications(query: GetCurrentNotificationsQuery): Promise<GetCurrentNotificationsQueryResult>
}

/** Vehicle details
*/
// Source: cs-fleetmonitoring-api.gener8.yaml:222
export interface Vehicle {

	/** vehicle id
	*/
  	vehicleId: string,

	/** fleet id
	*/
  	fleetId?: (string) | undefined,

	/** vehicle name
	*/
  	name?: (string) | undefined,

	/** vehicle description
	*/
  	description?: (string) | undefined,

	/** image url
	*/
  	imageUrl?: (string) | undefined,

	/** registration
	*/
  	registration?: (string) | undefined,

	/** vehicleType
	*/
  	vehicleType?: (VehicleType) | undefined,

	/** connectivity Mode
	*/
  	connectivityMode?: (ConnectivityMode) | undefined,

	/** driving Mode
	*/
  	drivingMode?: (DrivingMode) | undefined,

	/** health state
	*/
  	healthState?: (HealthState) | undefined,

	/** passenger count
	*/
  	passengerCount?: (number) | undefined,

	/** maximum passenger count
	*/
  	maxPassengerCount?: (number) | undefined,

	/** Fuel level
	*/
  	fuelLevel?: (number) | undefined,

	/** next maintenance date
	*/
  	nextMaintenanceAt?: (string) | undefined,

	/** last alive date
	*/
  	lastAliveAt?: (string) | undefined,

	/** historical vehicle information
	*/
  	historyInfo?: (HistoryInfo) | undefined
}

/** Fleet details
*/
// Source: cs-fleetmonitoring-api.gener8.yaml:274
export interface Fleet {

	/** Fleet info
	*/
  	fleetInfo: ClientItemInfo,

	/** vehicle name
	*/
  	name?: (string) | undefined,

	/** vehicle description
	*/
  	description?: (string) | undefined,

	/** image url
	*/
  	imageUrl?: (string) | undefined,

	/** historical fleet information
	*/
  	historyInfo?: (HistoryInfo) | undefined
}

/** Kpi details
*/
// Source: cs-fleetmonitoring-api.gener8.yaml:293
export interface Kpi {

	/** KPI info
	*/
  	kpiInfo: ClientItemInfo,

	/** Value
	*/
  	value?: (number) | undefined,

	/** Min value
	*/
  	min?: (number) | undefined,

	/** Max value
	*/
  	max?: (number) | undefined,

	/** KPI type
	*/
  	kpiType?: (KpiType) | undefined,

	/** Trend type
	*/
  	trendType?: (TrendType) | undefined,

	/** historical vehicle information
	*/
  	historyInfo?: (HistoryInfo) | undefined
}

/** Vehicle positions aggregate
*/
// Source: cs-fleetmonitoring-api.gener8.yaml:318
export interface VehiclePositions {

	/** vehicle id
	*/
  	vehicleId: string,

	/** Geo position info
	*/
  	positions: PositionInfo[]
}

/** Vehicle position info
*/
// Source: cs-fleetmonitoring-api.gener8.yaml:328
export interface PositionInfo {

	/** vehicle position timestamp
	*/
  	timestamp: string,

	/** Geo position
	*/
  	position: GeoPoint
}

/** Saved UI settings
*/
// Source: cs-settings-api.gener8.yaml:54
export interface UserSettings {

	/** The key of the frontend settings
	*/
  	key: string,

	/** Actual settings (generic)
	*/
  	settings: any,

	/** FormatRevision of the settings
	*/
  	formatRevision: string
}

/** User notification
*/
// Source: cs-notifications-api.gener8.yaml:39
export interface UserNotification {

	/** The id of the notification
	*/
  	id: string,

	/** Notification title
	*/
  	title: string,

	/** Notification details
	*/
  	details?: (string) | undefined,

	/** The markTypes
	*/
  	markTypes?: (NotificationMarkType[]) | undefined
}

/** Item info
*/
// Source: common-classes.gener8.yaml:2
export interface ClientItemInfo {

	/** item id
	*/
  	id: string,

	/** client id
	*/
  	clientId: string
}

/** History info
*/
// Source: common-classes.gener8.yaml:12
export interface HistoryInfo {

	/** Id of history entry
	*/
  	id: string,

	/** Date of creation
	*/
  	date: string,

	/** Creator of the entry in History
	*/
  	editor: string,

	/** Version of the history entry
	*/
  	version: string
}

/** Client details
*/
// Source: common-classes.gener8.yaml:28
export interface ClientDetails {

	/** Client id
	*/
  	id: string,

	/** Name
	*/
  	name: string,

	/** Client description
	*/
  	description?: (string) | undefined,

	/** imageUrl of client's logo image
	*/
  	imageUrl?: (string) | undefined
}

/** User details
*/
// Source: common-classes.gener8.yaml:44
export interface UserDetails {

	/** User id
	*/
  	id: string,

	/** Salutation
	*/
  	salutation?: (string) | undefined,

	/** FirstName
	*/
  	firstName?: (string) | undefined,

	/** LastName
	*/
  	lastName?: (string) | undefined,

	/** Email
	*/
  	email: string,

	/** Phone
	*/
  	phone?: (string) | undefined,

	/** imageUrl
	*/
  	imageUrl?: (string) | undefined,

	/** timezoneId
	*/
  	timezoneId: string,

	/** unitSystem
	*/
  	unitSystem: UnitSystemType,

	/** language
	*/
  	language: LanguageType,

	/** lastLoginAt
	*/
  	lastLoginAt?: (string) | undefined
}

/** Sorting definition
*/
// Source: common-classes.gener8.yaml:81
export interface Sorting {

	/** attribute to sort by
	*/
  	attribute: string,

	/** Sorting direction (ascending or descending)
	*/
  	direction: SortDirection,

	/** Sorting Mode (min, max, avg, sum)
	*/
  	mode: SortMode,

	/** Sorting of nulls/missing values (first or last)
	*/
  	nulls: SortNulls
}

/** Geographical coordinates (WGS84)
*/
// Source: common-classes.gener8.yaml:99
export interface GeoPoint {

	/** Latitude north
	*/
  	lat: number,

	/** Longitude east
	*/
  	lng: number
}

/** Modifications to Vehicle
*/
// Source: cs-fleetmonitoring-api.gener8.yaml:222
export interface VehicleModification {

	/** [Modifier] vehicle id
	*/
  	vehicleIdModification?: (Modifier<string>) | undefined,

	/** [Modifier] fleet id
	*/
  	fleetIdModification?: (Modifier<(string) | undefined>) | undefined,

	/** [Modifier] vehicle name
	*/
  	nameModification?: (Modifier<(string) | undefined>) | undefined,

	/** [Modifier] vehicle description
	*/
  	descriptionModification?: (Modifier<(string) | undefined>) | undefined,

	/** [Modifier] image url
	*/
  	imageUrlModification?: (Modifier<(string) | undefined>) | undefined,

	/** [Modifier] registration
	*/
  	registrationModification?: (Modifier<(string) | undefined>) | undefined,

	/** [Modifier] vehicleType
	*/
  	vehicleTypeModification?: (Modifier<(VehicleType) | undefined>) | undefined,

	/** [Modifier] connectivity Mode
	*/
  	connectivityModeModification?: (Modifier<(ConnectivityMode) | undefined>) | undefined,

	/** [Modifier] driving Mode
	*/
  	drivingModeModification?: (Modifier<(DrivingMode) | undefined>) | undefined,

	/** [Modifier] health state
	*/
  	healthStateModification?: (Modifier<(HealthState) | undefined>) | undefined,

	/** [Modifier] passenger count
	*/
  	passengerCountModification?: (Modifier<(number) | undefined>) | undefined,

	/** [Modifier] maximum passenger count
	*/
  	maxPassengerCountModification?: (Modifier<(number) | undefined>) | undefined,

	/** [Modifier] Fuel level
	*/
  	fuelLevelModification?: (Modifier<(number) | undefined>) | undefined,

	/** [Modifier] next maintenance date
	*/
  	nextMaintenanceAtModification?: (Modifier<(string) | undefined>) | undefined,

	/** [Modifier] last alive date
	*/
  	lastAliveAtModification?: (Modifier<(string) | undefined>) | undefined,

	/** [Modifier] historical vehicle information
	*/
  	historyInfoModification?: (Modifier<(HistoryInfo) | undefined>) | undefined
}

/** Modifications to Fleet
*/
// Source: cs-fleetmonitoring-api.gener8.yaml:274
export interface FleetModification {

	/** [Modification] Fleet info
	*/
  	fleetInfoModification?: (ClientItemInfoModification) | undefined,

	/** [Modifier] vehicle name
	*/
  	nameModification?: (Modifier<(string) | undefined>) | undefined,

	/** [Modifier] vehicle description
	*/
  	descriptionModification?: (Modifier<(string) | undefined>) | undefined,

	/** [Modifier] image url
	*/
  	imageUrlModification?: (Modifier<(string) | undefined>) | undefined,

	/** [Modifier] historical fleet information
	*/
  	historyInfoModification?: (Modifier<(HistoryInfo) | undefined>) | undefined
}

/** Modifications to Kpi
*/
// Source: cs-fleetmonitoring-api.gener8.yaml:293
export interface KpiModification {

	/** [Modification] KPI info
	*/
  	kpiInfoModification?: (ClientItemInfoModification) | undefined,

	/** [Modifier] Value
	*/
  	valueModification?: (Modifier<(number) | undefined>) | undefined,

	/** [Modifier] Min value
	*/
  	minModification?: (Modifier<(number) | undefined>) | undefined,

	/** [Modifier] Max value
	*/
  	maxModification?: (Modifier<(number) | undefined>) | undefined,

	/** [Modifier] KPI type
	*/
  	kpiTypeModification?: (Modifier<(KpiType) | undefined>) | undefined,

	/** [Modifier] Trend type
	*/
  	trendTypeModification?: (Modifier<(TrendType) | undefined>) | undefined,

	/** [Modifier] historical vehicle information
	*/
  	historyInfoModification?: (Modifier<(HistoryInfo) | undefined>) | undefined
}

/** Modifications to VehiclePositions
*/
// Source: cs-fleetmonitoring-api.gener8.yaml:318
export interface VehiclePositionsModification {

	/** [Modifier] vehicle id
	*/
  	vehicleIdModification?: (Modifier<string>) | undefined,

	/** [Modifier] Geo position info
	*/
  	positionsModification?: (Modifier<PositionInfo[]>) | undefined
}

/** Modifications to PositionInfo
*/
// Source: cs-fleetmonitoring-api.gener8.yaml:328
export interface PositionInfoModification {

	/** [Modifier] vehicle position timestamp
	*/
  	timestampModification?: (Modifier<string>) | undefined,

	/** [Modification] Geo position
	*/
  	positionModification?: (GeoPointModification) | undefined
}

/** Modifications to UserSettings
*/
// Source: cs-settings-api.gener8.yaml:54
export interface UserSettingsModification {

	/** [Modifier] The key of the frontend settings
	*/
  	keyModification?: (Modifier<string>) | undefined,

	/** [Modifier] Actual settings (generic)
	*/
  	settingsModification?: (Modifier<any>) | undefined,

	/** [Modifier] FormatRevision of the settings
	*/
  	formatRevisionModification?: (Modifier<string>) | undefined
}

/** Modifications to UserNotification
*/
// Source: cs-notifications-api.gener8.yaml:39
export interface UserNotificationModification {

	/** [Modifier] The id of the notification
	*/
  	idModification?: (Modifier<string>) | undefined,

	/** [Modifier] Notification title
	*/
  	titleModification?: (Modifier<string>) | undefined,

	/** [Modifier] Notification details
	*/
  	detailsModification?: (Modifier<(string) | undefined>) | undefined,

	/** [Modifier] The markTypes
	*/
  	markTypesModification?: (Modifier<(NotificationMarkType[]) | undefined>) | undefined
}

/** Modifications to ClientItemInfo
*/
// Source: common-classes.gener8.yaml:2
export interface ClientItemInfoModification {

	/** [Modifier] item id
	*/
  	idModification?: (Modifier<string>) | undefined,

	/** [Modifier] client id
	*/
  	clientIdModification?: (Modifier<string>) | undefined
}

/** Modifications to HistoryInfo
*/
// Source: common-classes.gener8.yaml:12
export interface HistoryInfoModification {

	/** [Modifier] Id of history entry
	*/
  	idModification?: (Modifier<string>) | undefined,

	/** [Modifier] Date of creation
	*/
  	dateModification?: (Modifier<string>) | undefined,

	/** [Modifier] Creator of the entry in History
	*/
  	editorModification?: (Modifier<string>) | undefined,

	/** [Modifier] Version of the history entry
	*/
  	versionModification?: (Modifier<string>) | undefined
}

/** Modifications to ClientDetails
*/
// Source: common-classes.gener8.yaml:28
export interface ClientDetailsModification {

	/** [Modifier] Client id
	*/
  	idModification?: (Modifier<string>) | undefined,

	/** [Modifier] Name
	*/
  	nameModification?: (Modifier<string>) | undefined,

	/** [Modifier] Client description
	*/
  	descriptionModification?: (Modifier<(string) | undefined>) | undefined,

	/** [Modifier] imageUrl of client's logo image
	*/
  	imageUrlModification?: (Modifier<(string) | undefined>) | undefined
}

/** Modifications to UserDetails
*/
// Source: common-classes.gener8.yaml:44
export interface UserDetailsModification {

	/** [Modifier] User id
	*/
  	idModification?: (Modifier<string>) | undefined,

	/** [Modifier] Salutation
	*/
  	salutationModification?: (Modifier<(string) | undefined>) | undefined,

	/** [Modifier] FirstName
	*/
  	firstNameModification?: (Modifier<(string) | undefined>) | undefined,

	/** [Modifier] LastName
	*/
  	lastNameModification?: (Modifier<(string) | undefined>) | undefined,

	/** [Modifier] Email
	*/
  	emailModification?: (Modifier<string>) | undefined,

	/** [Modifier] Phone
	*/
  	phoneModification?: (Modifier<(string) | undefined>) | undefined,

	/** [Modifier] imageUrl
	*/
  	imageUrlModification?: (Modifier<(string) | undefined>) | undefined,

	/** [Modifier] timezoneId
	*/
  	timezoneIdModification?: (Modifier<string>) | undefined,

	/** [Modifier] unitSystem
	*/
  	unitSystemModification?: (Modifier<UnitSystemType>) | undefined,

	/** [Modifier] language
	*/
  	languageModification?: (Modifier<LanguageType>) | undefined,

	/** [Modifier] lastLoginAt
	*/
  	lastLoginAtModification?: (Modifier<(string) | undefined>) | undefined
}

/** Modifications to Sorting
*/
// Source: common-classes.gener8.yaml:81
export interface SortingModification {

	/** [Modifier] attribute to sort by
	*/
  	attributeModification?: (Modifier<string>) | undefined,

	/** [Modifier] Sorting direction (ascending or descending)
	*/
  	directionModification?: (Modifier<SortDirection>) | undefined,

	/** [Modifier] Sorting Mode (min, max, avg, sum)
	*/
  	modeModification?: (Modifier<SortMode>) | undefined,

	/** [Modifier] Sorting of nulls/missing values (first or last)
	*/
  	nullsModification?: (Modifier<SortNulls>) | undefined
}

/** Modifications to GeoPoint
*/
// Source: common-classes.gener8.yaml:99
export interface GeoPointModification {

	/** [Modifier] Latitude north
	*/
  	latModification?: (Modifier<number>) | undefined,

	/** [Modifier] Longitude east
	*/
  	lngModification?: (Modifier<number>) | undefined
}

/** getFleets Parameter
*/
// Source: cs-fleetmonitoring-api.gener8.yaml:48
export interface GetFleetsQuery {

	/** The client id to fetch the fleets from
	*/
  	clientId: string
}

/** getFleets Result
*/
// Source: cs-fleetmonitoring-api.gener8.yaml:48
export interface GetFleetsQueryResult {

	/** The list of fleets
	*/
  	fleets: Fleet[],

	/** The number of total hits
	*/
  	totalHits: number
}

/** getVehicles Parameter
*/
// Source: cs-fleetmonitoring-api.gener8.yaml:63
export interface GetVehiclesQuery {

	/** The client id to fetch the vehicles from
	*/
  	clientId: string
}

/** getVehicles Result
*/
// Source: cs-fleetmonitoring-api.gener8.yaml:63
export interface GetVehiclesQueryResult {

	/** All vehicles contained in the client
	*/
  	vehicles: Vehicle[],

	/** The number of total hits
	*/
  	totalHits: number
}

/** getFleetVehicles Parameter
*/
// Source: cs-fleetmonitoring-api.gener8.yaml:78
export interface GetFleetVehiclesQuery {

	/** The fleet id to fetch the vehicles from
	*/
  	fleetId: string
}

/** getFleetVehicles Result
*/
// Source: cs-fleetmonitoring-api.gener8.yaml:78
export interface GetFleetVehiclesQueryResult {

	/** All vehicles contained in the fleet
	*/
  	vehicles: Vehicle[],

	/** The number of total hits
	*/
  	totalHits: number
}

/** getVehiclePositions Parameter
*/
// Source: cs-fleetmonitoring-api.gener8.yaml:93
export interface GetVehiclePositionsQuery {

	/** The client id to fetch the vehicle positions from
	*/
  	clientId: string,

	/** The start date to fetch
	*/
  	startDate: string,

	/** The end date to fetch, If left null, endDate is considered as now
	*/
  	endDate?: (string) | undefined,

	/** The fleet ids to fetch the vehicle positions from
	*/
  	fleetIds?: (string[]) | undefined
}

/** getVehiclePositions Result
*/
// Source: cs-fleetmonitoring-api.gener8.yaml:93
export interface GetVehiclePositionsQueryResult {

	/** All vehicle positions aggregats contained in the query result
	*/
  	vehiclePositions: VehiclePositions[]
}

/** getKpis Parameter
*/
// Source: cs-fleetmonitoring-api.gener8.yaml:114
export interface GetKpisQuery {

	/** The client id to fetch the KPIs from
	*/
  	clientId: string,

	/** KPI types to fetch
	*/
  	kpiTypes?: (KpiType[]) | undefined
}

/** getKpis Result
*/
// Source: cs-fleetmonitoring-api.gener8.yaml:114
export interface GetKpisQueryResult {

	/** KPIs for this client or for the types specified
	*/
  	kpis: Kpi[]
}

/** createVehicle Parameter
*/
// Source: cs-fleetmonitoring-api.gener8.yaml:131
export interface CreateVehicleCommand {

	/** attributes of the new fleet item
	*/
  	vehicle: Vehicle
}

/** createVehicle Result
*/
// Source: cs-fleetmonitoring-api.gener8.yaml:131
export interface CreateVehicleResult {

	/** The id of the newly created vehicle
	*/
  	id: string
}

/** modifyVehicle Parameter
*/
// Source: cs-fleetmonitoring-api.gener8.yaml:144
export interface ModifyVehicleCommand {

	/** ID of the modified vehicle
	*/
  	id: string,

	/** modifications to the vehicle attributes
	*/
  	vehicleDetails: Vehicle
}

/** modifyVehicle Result
*/
// Source: cs-fleetmonitoring-api.gener8.yaml:144
export interface ModifyVehicleResult {
}

/** deleteVehicle Parameter
*/
// Source: cs-fleetmonitoring-api.gener8.yaml:156
export interface DeleteVehicleCommand {

	/** ID of the vehicle to delete
	*/
  	id: string
}

/** deleteVehicle Result
*/
// Source: cs-fleetmonitoring-api.gener8.yaml:156
export interface DeleteVehicleResult {
}

/** createFleet Parameter
*/
// Source: cs-fleetmonitoring-api.gener8.yaml:165
export interface CreateFleetCommand {

	/** attributes of the new fleet item
	*/
  	fleet: Fleet
}

/** createFleet Result
*/
// Source: cs-fleetmonitoring-api.gener8.yaml:165
export interface CreateFleetResult {

	/** The id of the newly created fleet
	*/
  	id: string
}

/** modifyFleet Parameter
*/
// Source: cs-fleetmonitoring-api.gener8.yaml:178
export interface ModifyFleetCommand {

	/** ID of the modified fleet
	*/
  	id: string,

	/** modifications to the fleet attributes
	*/
  	fleetDetails: Fleet
}

/** modifyFleet Result
*/
// Source: cs-fleetmonitoring-api.gener8.yaml:178
export interface ModifyFleetResult {
}

/** deleteFleet Parameter
*/
// Source: cs-fleetmonitoring-api.gener8.yaml:190
export interface DeleteFleetCommand {

	/** ID of the fleet to delete
	*/
  	id: string
}

/** deleteFleet Result
*/
// Source: cs-fleetmonitoring-api.gener8.yaml:190
export interface DeleteFleetResult {
}

/** addVehicleToFleet Parameter
*/
// Source: cs-fleetmonitoring-api.gener8.yaml:199
export interface AddVehicleToFleetCommand {

	/** id of the vehicle
	*/
  	vehicleId: string,

	/** id of the fleet
	*/
  	fleetId: string
}

/** addVehicleToFleet Result
*/
// Source: cs-fleetmonitoring-api.gener8.yaml:199
export interface AddVehicleToFleetResult {
}

/** removeVehicleFromFleet Parameter
*/
// Source: cs-fleetmonitoring-api.gener8.yaml:210
export interface RemoveVehicleFromFleetCommand {

	/** id of the vehicle
	*/
  	VehicleId: string,

	/** id of the fleet
	*/
  	fleetId: string
}

/** removeVehicleFromFleet Result
*/
// Source: cs-fleetmonitoring-api.gener8.yaml:210
export interface RemoveVehicleFromFleetResult {
}

/** getUserSetting Parameter
*/
// Source: cs-settings-api.gener8.yaml:8
export interface GetUserSettingQuery {

	/** The key of the setting
	*/
  	key: string
}

/** getUserSetting Result
*/
// Source: cs-settings-api.gener8.yaml:8
export interface GetUserSettingQueryResult {

	/** Returned setting, null if not found
	*/
  	setting?: (UserSettings) | undefined
}

/** getUserSettings Parameter
*/
// Source: cs-settings-api.gener8.yaml:21
export interface GetUserSettingsQuery {

	/** The key prefix of the settings to retrieve
	*/
  	prefix?: (string) | undefined
}

/** getUserSettings Result
*/
// Source: cs-settings-api.gener8.yaml:21
export interface GetUserSettingsQueryResult {

	/** Returned settings
	*/
  	settings: UserSettings[]
}

/** deleteUserSettings Parameter
*/
// Source: cs-settings-api.gener8.yaml:35
export interface DeleteUserSettingsCommand {

	/** The user settings to delete
	*/
  	keys: string[]
}

/** deleteUserSettings Result
*/
// Source: cs-settings-api.gener8.yaml:35
export interface DeleteUserSettingsResult {
}

/** saveUserSettings Parameter
*/
// Source: cs-settings-api.gener8.yaml:44
export interface SaveUserSettingsCommand {

	/** The user settings to save
	*/
  	settings: UserSettings[]
}

/** saveUserSettings Result
*/
// Source: cs-settings-api.gener8.yaml:44
export interface SaveUserSettingsResult {
}

/** getCurrentNotifications Parameter
*/
// Source: cs-notifications-api.gener8.yaml:9
export interface GetCurrentNotificationsQuery {

	/** The mark types to fetch
	*/
  	markTypes?: (NotificationMarkType[]) | undefined
}

/** getCurrentNotifications Result
*/
// Source: cs-notifications-api.gener8.yaml:9
export interface GetCurrentNotificationsQueryResult {

	/** Returns notifications, null if not found
	*/
  	notifications: UserNotification[],

	/** The number of total hits
	*/
  	totalHits: number
}

/** markNotifications Parameter
*/
// Source: cs-notifications-api.gener8.yaml:26
export interface MarkNotificationsCommand {

	/** The notifications to mark
	*/
  	ids: string[],

	/** The type to mark the specified notifications
	*/
  	markType: NotificationMarkType
}

/** markNotifications Result
*/
// Source: cs-notifications-api.gener8.yaml:26
export interface MarkNotificationsResult {
}

/** a new knowledge entry was created
*/
// Source: cs-settings-api.gener8.yaml:68
export interface UserSettingsModified {

	/** new settings
	*/
  	settings: UserSettings
}

/** settings was deleted
*/
// Source: cs-settings-api.gener8.yaml:75
export interface UserSettingsDeleted {
}


/** KPI Type
*/
// Source: cs-fleetmonitoring-api.gener8.yaml:339
export enum KpiType {
	/** autonomous time since ignition
	*/
	autonomousTimeSinceIgnition = "autonomousTimeSinceIgnition",

	/** autonomous time total
	*/
	autonomousTimeTotal = "autonomousTimeTotal",

	/** smooth riding violation count since ignition
	*/
	smoothRidingViolationCountSinceIgnition = "smoothRidingViolationCountSinceIgnition",

	/** without alarm time
	*/
	withoutAlarmTime = "withoutAlarmTime",

}

/** Trend type
*/
// Source: cs-fleetmonitoring-api.gener8.yaml:351
export enum TrendType {
	/** Up
	*/
	up = "up",

	/** Down
	*/
	down = "down",

	/** No change
	*/
	NoChange = "NoChange",

}

/** POI type
*/
// Source: cs-fleetmonitoring-api.gener8.yaml:361
export enum PoiType {
	/** Mobile Networks
	*/
	mobileNetworks = "mobileNetworks",

	/** Infrastructure
	*/
	infrastructure = "infrastructure",

	/** Stops
	*/
	stops = "stops",

}

/** Vehicle Type
*/
// Source: cs-fleetmonitoring-api.gener8.yaml:371
export enum VehicleType {
	/** Car
	*/
	car = "car",

	/** Bus
	*/
	bus = "bus",

	/** Truck
	*/
	truck = "truck",

}

/** Driving Mode
*/
// Source: cs-fleetmonitoring-api.gener8.yaml:381
export enum DrivingMode {
	/** Manual
	*/
	manual = "manual",

	/** Automatic
	*/
	automatic = "automatic",

	/** Autonomous
	*/
	autonomous = "autonomous",

}

/** Connectivity Mode
*/
// Source: cs-fleetmonitoring-api.gener8.yaml:391
export enum ConnectivityMode {
	/** Bluetooth
	*/
	bluetooth = "bluetooth",

	/** Wifi
	*/
	wifi = "wifi",

	/** GSM
	*/
	gsm = "gsm",

}

/** Health state
*/
// Source: cs-fleetmonitoring-api.gener8.yaml:401
export enum HealthState {
	/** Good
	*/
	ok = "ok",

	/** Warning
	*/
	warn = "warn",

	/** Fatal
	*/
	fatal = "fatal",

}

/** Notification Mark Type
*/
// Source: cs-notifications-api.gener8.yaml:56
export enum NotificationMarkType {
	/** mark as favorite
	*/
	favorite = "favorite",

	/** mark as read
	*/
	read = "read",

	/** mark as deleted
	*/
	deleted = "deleted",

}

/** Sort Direction
*/
// Source: common-enums.gener8.yaml:2
export enum SortDirection {
	/** Ascending order
	*/
	Asc = "Asc",

	/** Descending order
	*/
	Desc = "Desc",

}

/** Sort Mode for multiple elements
*/
// Source: common-enums.gener8.yaml:10
export enum SortMode {
	/** Sort by largest element
	*/
	Max = "Max",

	/** Sort by smallest element
	*/
	Min = "Min",

	/** Sort by average of all elements
	*/
	Avg = "Avg",

	/** Sort by sum of all elements
	*/
	Sum = "Sum",

}

/** Sort Position for null/empty fields
*/
// Source: common-enums.gener8.yaml:22
export enum SortNulls {
	/** Sort nulls first
	*/
	First = "First",

	/** Sort nulls last
	*/
	Last = "Last",

}

/** Language
*/
// Source: common-enums.gener8.yaml:30
export enum LanguageType {
	/** Deutsch
	*/
	de = "de",

	/** English
	*/
	en = "en",

}

/** UnitSystem Type
*/
// Source: common-enums.gener8.yaml:38
export enum UnitSystemType {
	/** Metric
	*/
	metric = "metric",

	/** Imperial
	*/
	imperial = "imperial",

}





// Privileges
export const Privileges = {
		allAccess: "allAccess", // Unrestricted access to all apis
		createVehicle: "createVehicle", // Create a vehicle
		deleteVehicle: "deleteVehicle", // Delete a vehicle
		modifyVehicle: "modifyVehicle", // Modify a vehicle
		createFleet: "createFleet", // Create a fleet
		deleteFleet: "deleteFleet", // Delete a fleet
		modifyFleet: "modifyFleet", // Modify a fleet
		readOtherUserSettings: "readOtherUserSettings", // Read other users' settings
		writeOtherUserSettings: "writeOtherUserSettings", // Write other users' settings
		writeGlobalUserSettings: "writeGlobalUserSettings", // Write global settings
		readNotifications: "readNotifications", // Read user notifications
		writeNotifications: "writeNotifications", // Write user notifications
		getFleets: "getFleets", // List fleets.
		getVehicles: "getVehicles", // Get all the client vehicles
		getFleetVehicles: "getFleetVehicles", // Get the vehicles
		getVehiclePositions: "getVehiclePositions", // Get the vehicle positions
		getKpis: "getKpis", // Get all the client KPIs
		addVehicleToFleet: "addVehicleToFleet", // Add a vehicle to a fleet
		removeVehicleFromFleet: "removeVehicleFromFleet", // Remove a vehicle from a fleet
}
